services:
  - type: web
    name: vocal-height-guesser
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn height_guesser.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9 