services:
  - type: web
    name: vocal-height-guesser
    env: docker
    repo: https://github.com/dejoski/vocal-height-guesser.git
    branch: main
    buildCommand: docker build -t vocal-height-guesser -f deployment/Dockerfile .
    startCommand: docker run -p $PORT:5000 vocal-height-guesser 